apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bike-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bike-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bike-api
    spec:
      containers:
        - name: bike-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
