replicaCount: 1

image:
  repository: bikeapi
  tag: test
  pullPolicy: IfNotPresent

service:
  enabled: true
  annotations: {}
  type: LoadBalancer
  port: 8080

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false

resources: {}
